# Generated by Django 4.2.20 on 2025-04-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationModel',
        ),
    ]
