# Generated by Django 4.2.20 on 2025-04-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_rename_registration_registrationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='sex',
        ),
    ]
