# Generated by Django 4.2.20 on 2025-04-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_delete_person_remove_registrationmodel_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonimous', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(default='Male', max_length=100)),
                ('regIdFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.registrationmodel')),
            ],
        ),
    ]
