# Generated by Django 4.2.20 on 2025-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.CharField(default='Название товара', max_length=100)),
                ('goodPic', models.ImageField(blank=True, null=True, upload_to='goods/')),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='RegistrationModel',
        ),
    ]
